### ISSUE TITLE
Route request: allowable vehicle types

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/sumo-connector#1]
Are the allowable vehicle types in the request limited to 'DEFAULT_BIKETYPE', 'DEFAULT_PEDTYPE', 'DEFAULT_VEHTYPE', 'bike_bicycle', 'bus_bus', 'emergency', 'ped_pedestrian', 'rail_rail', 'tram_tram', 'truck_truck', 'veh_passenger'? If so, I can implement it in the TMT as an enum. Or are there other ones.

And why the double names, e.g. truck_truck and not just truck?

**Comment by behrisch** [comment]
The vehicle type can be an arbitrary string. It currently is (in the sumo connector) a combination of a specific string and the vehicle class which is one of a fixed list of values, see https://github.com/eclipse/sumo/blob/master/src/utils/common/SUMOVehicleClass.cpp#L43. I think we should limit the choice to "passenger", "truck", "emergency" and "ignoring" (which can drive everywhere). Maybe also "bus" and "bicycle" if you think it is useful.

**Comment by behrisch** [comment]
Closed since there are no further remarks. If you feel there is still an open point here, please reopen.
