### ISSUE TITLE
Road block - how to model it?

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/sumo-connector#8]
Is it possible to place a roadblock, allowing regular traffic to pass very slowly? Or only allow emergency traffic to pass? How can we do that?

**Comment by behrisch** [comment]
We can reduce capacity by simply adding a stopped vehicle. We could "abuse" a routing request with a single location here or add a new message type. For blocking streets completely I would use an affected area message which also allows to specify which vehicle classes can still pass. Reducing the speed is possible with sumo but there is currently not a message which conveys this information. We could add this to the affected area as well.

**Comment by behrisch** [comment]
If there is still something unclear please reopen.
